version: '3'

services:
  node:
    restart: always
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.31
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
