version: '3.7'
services:
  node:
    restart: always
    environment:
      - HOST=mongo
    build: .
    ports:
      - 3001:3001
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
