version: '3'

services:
  node:
    restart: always
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    image: mysql:5.7.31
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=SSYS
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
